# Generated by Django 3.2.8 on 2021-10-14 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='upload_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modify_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
