# Generated by Django 3.2.7 on 2021-10-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='last_upload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
