# Generated by Django 3.2.8 on 2021-10-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_image_upload_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_by',
            new_name='owner',
        ),
    ]
