# Generated by Django 3.2.7 on 2021-10-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_picture_upload_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='upload_by',
        ),
    ]
