# Generated by Django 3.2.8 on 2021-10-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_upload_by_image_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='owner',
            new_name='upload_by',
        ),
    ]
