# Generated by Django 3.2.8 on 2021-10-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_owner_image_upload_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
