# Generated by Django 3.2.7 on 2021-10-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_picture_upload_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='upload_by',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
